### ISSUE TITLE
Awesome project! 

### ISSUE THREAD

**Issue by AaronJan** [Neamar/featureless-job-queue#5]
I tried `Kue` and `Bull` before, but they are too heavy for my project (and some other reasons, like performance), so I done a little searching, found `featureless-job-queue`, really simple and fast!

But I'm using TypeScript in my project, and `async` feels kind of old to me, so I decided to write a new project that using things I learned from `featureless-job-queue`, I just done it: [StanchionJS](https://github.com/AaronJan/StanchionJS), and will continue to perfect it.

Thank you, cheers!

**Comment by Neamar** [comment]
Awesome! Thanks for sharing :)
